### ISSUE TITLE
Rust Display bug

### ISSUE THREAD

**Issue by cjgratacos** [akinsho/dependency-assist.nvim#3]
First thanks for the awesome project. Currently there is a small visual bug on Rust where the version display are not currently align:

![Screenshot_2021-02-22_22-27-14](https://user-images.githubusercontent.com/5974887/108799008-3534e780-755d-11eb-953a-dabe76161e68.png)

```toml
[package]
name = "test-rs"
version = "0.1.0"
authors = ["cjgratacos"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = {version = "0.8" }
clap = { version = "3.0.0-beta.2" }
thiserror = { version = "1.0" }

```
